server:
  port: 8089

security:
  oauth2:
    client:
      clientId: m1
      clientSecret: s1
      accessTokenUri: http://localhost:9999/idm/oauth/token
      userAuthorizationUri: http://localhost:9999/idm/oauth/authorize
      tokenName: access_token
    resource:
      userInfoUri: http://localhost:9999/idm/user
